version: '3.8'

services:

  # Nuovo database PostgreSQL per Keycloak
  keycloak-postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: keycloak              # Utente dedicato per Keycloak
      POSTGRES_PASSWORD: keycloakpassword  # Password per il db Keycloak
      POSTGRES_DB: keycloak                # Nome del database Keycloak
    ports:
      - 5433:5432                          # Porta separata per evitare conflitti con l'altro DB
    volumes:
      - ./docker_volumes/keycloak_postgres:/var/lib/postgresql/data
    networks:
      - example-network

  # Database PostgreSQL per l'applicazione
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker_volumes/postgres:/var/lib/postgresql/data
    networks:
      - example-network

  # Servizio Keycloak con il proprio database PostgreSQL dedicato
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-postgres    # Nuovo host per il db Keycloak
      KC_DB_URL_DATABASE: keycloak         # Nome del nuovo database Keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpassword     # Nuova password per il db Keycloak
      KC_HOSTNAME: localhost
    ports:
      - 8080:8080
    volumes:
      - ./docker_volumes/keycloak:/opt/keycloak/data
    networks:
      - example-network
    depends_on:
      - keycloak-postgres                  # Dipendenza dal nuovo database Keycloak
    command:
      - start-dev

  # Servizio Spring Boot (Java App)
  app:
    build:
      context: ./ # Utilizza il Dockerfile nella cartella del progetto
      dockerfile: Dockerfile           # Nome del Dockerfile
    container_name: java-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: docker
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: 'true'
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/ExampleRealm
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/ExampleRealm/protocol/openid-connect/certs
    ports:
      - 8081:8081
    volumes:
      - ./ExampleProject-Core:/app
    depends_on:
      - keycloak
      - postgres
    networks:
      - example-network

networks:
  example-network:
    driver: bridge
