server:
  port: 8081
  servlet:
    context-path: /api
  error:
    include-message: always

spring:
  datasource:
    #Docker deploy url
    #url: jdbc:postgresql://172.18.0.3:5432/postgres
    #Local deploy url
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ExampleRealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true

logging:
  level:
    com.examplecode.core: DEBUG

jwt:
  auth:
    converter:
      resource-id: example-application-client
      principal-attribute: principal_username

keycloak:
  base_url: ${KEYCLOAK_BASE_URL}
  realm: ${KEYCLOAK_REALM}
  auth:
    url: ${KEYCLOAK_AUTH_URL}
  users:
    url: ${KEYCLOAK_USERS_URL}
  client:
    id: ${KEYCLOAK_CLIENT_ID}
    secret: ${KEYCLOAK_CLIENT_SECRET}
  admin:
    email: ${KEYCLOAK_ADMIN_EMAIL}
    password: ${KEYCLOAK_ADMIN_PASSWORD}